url:
baseurl:

# Site settings
title: O.D.I.N.
email: your-email@domain.com
description: "We do stuff."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mayank Badola
  pic: 1.jpg
  position: Org Core Member
  social:
    - title: twitter
      url: https://twitter.com/mbad0la
    - title: github
      url: http://mbad0la.github.io

- name: Divjot Singh
  pic: 2.jpg
  position: Org Core Member
  social:
    - title: twitter
      url: https://twitter.com/bogas04
    - title: github
      url: http://bogas04.github.io

- name: Sahil Dua
  pic: 3.jpg
  position: Org Core Member
  social:
    - title: twitter
      url: https://twitter.com/sahildua2305
    - title: github
      url: http://github.com/sahildua2305

- name: Tarasha Khurana
  pic: 4.jpeg
  position: Collaborator

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/o-d-i-n

# Postal address (add as many lines as necessary)
address:
  - line: NSIT, Dwarka Sector 3
  - line: New Delhi, 110075

# Build settings
markdown: kramdown
permalink: pretty
